/*
 * ClassManageInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.rongjun.zheng.view;

import java.sql.Connection;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.rongjun.zheng.dao.GradeDao;
import com.rongjun.zheng.dao.SchoolClassDao;
import com.rongjun.zheng.dao.StudentDao;
import com.rongjun.zheng.model.Grade;
import com.rongjun.zheng.model.SchoolClass;
import com.rongjun.zheng.util.DbUtil;

/**
 *
 * @author  __USER__
 */
public class ClassManageInterFrm extends javax.swing.JInternalFrame {
	SchoolClassDao schoolClassDao = new SchoolClassDao();
	GradeDao gradeDao = new GradeDao();
	StudentDao studentDao=new StudentDao();
	DbUtil dbUtil = new DbUtil();

	/** Creates new form ClassManageInterFrm */
	public ClassManageInterFrm() {
		initComponents();
		this.fillGrade();
		this.fillTable(new SchoolClass());
		this.setLocation(400, 100);
	}

	public void fillGrade() {
		this.grade_jcb.removeAllItems();
		this.jcb_grade.removeAllItems();
		Connection con = null;
		Grade grade = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = gradeDao.gradeList(con, new Grade());
			while (rs.next()) {
				grade = new Grade();
				grade.setId(rs.getInt(1));
				grade.setGradeName(rs.getString(2));
				grade.setGradeRemark(rs.getString(3));
				this.grade_jcb.addItem(grade);
				this.jcb_grade.addItem(grade);

			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	public void fillTable(SchoolClass schoolclass) {
		DefaultTableModel dtm = (DefaultTableModel) this.Jt_ClassTable
				.getModel();
		dtm.setRowCount(0);
		Connection con = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = schoolClassDao.classList(con, schoolclass);
			while (rs.next()) {
				String[] row = { "" + rs.getInt("id"),
						rs.getString("className"), rs.getString("gradeName"),
						rs.getString("classRemark") };
				dtm.addRow(row);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jScrollPane1 = new javax.swing.JScrollPane();
Jt_ClassTable = new javax.swing.JTable();
jLabel1 = new javax.swing.JLabel();
jtf_id = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
jtf_className = new javax.swing.JTextField();
jLabel3 = new javax.swing.JLabel();
jcb_grade = new javax.swing.JComboBox();
jLabel4 = new javax.swing.JLabel();
jScrollPane2 = new javax.swing.JScrollPane();
jta_classRemark = new javax.swing.JTextArea();
jb_modify = new javax.swing.JButton();
jb_delete = new javax.swing.JButton();
jLabel5 = new javax.swing.JLabel();
className_jtf = new javax.swing.JTextField();
jLabel6 = new javax.swing.JLabel();
grade_jcb = new javax.swing.JComboBox();
jButton1 = new javax.swing.JButton();
jButton2 = new javax.swing.JButton();

setClosable(true);
setIconifiable(true);
setTitle("\u73ed\u7ea7\u7ef4\u62a4\u7cfb\u7edf");

Jt_ClassTable.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		
	},
	new String [] {
		"编号", "班级名", "年段", "班级备注"
	}
) {
	boolean[] canEdit = new boolean [] {
		false, true, true, true
	};

	public boolean isCellEditable(int rowIndex, int columnIndex) {
		return canEdit [columnIndex];
	}
});
Jt_ClassTable.addMouseListener(new java.awt.event.MouseAdapter() {
public void mousePressed(java.awt.event.MouseEvent evt) {
Jt_ClassTableMousePressed(evt);
}
});
jScrollPane1.setViewportView(Jt_ClassTable);

jLabel1.setText("\u7f16\u53f7");

jtf_id.setEditable(false);

jLabel2.setText("\u73ed\u7ea7\u540d");

jLabel3.setText("\u5e74\u6bb5");


jLabel4.setText("\u73ed\u7ea7\u5907\u6ce8");

jta_classRemark.setColumns(20);
jta_classRemark.setRows(5);
jScrollPane2.setViewportView(jta_classRemark);

jb_modify.setText("\u4fee\u6539");
jb_modify.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jb_modifyActionPerformed(evt);
}
});

jb_delete.setText("\u5220\u9664");
jb_delete.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jb_deleteActionPerformed(evt);
}
});

jLabel5.setText("\u73ed\u7ea7\u540d");

jLabel6.setText("\u5e74\u6bb5");

jButton1.setText("\u67e5\u8be2");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});

jButton2.setText("\u5168\u90e8\u663e\u793a");
jButton2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton2ActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel3)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jcb_grade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addComponent(jb_modify))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(30, 30, 30)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jLabel2)
.addComponent(jLabel4))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
.addComponent(jtf_className, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createSequentialGroup()
.addGap(61, 61, 61)
.addComponent(jb_delete)))
.addGap(20, 20, 20))
.addGroup(layout.createSequentialGroup()
.addGap(26, 26, 26)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel5)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(className_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel6)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(grade_jcb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
.addContainerGap(133, Short.MAX_VALUE))
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(26, Short.MAX_VALUE))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel5)
.addComponent(jLabel6)
.addComponent(className_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(grade_jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jButton2)
.addComponent(jButton1))
.addGap(18, 18, 18)
.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1)
.addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel2)
.addComponent(jtf_className, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3)
.addComponent(jcb_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel4)))
.addGroup(layout.createSequentialGroup()
.addGap(9, 9, 9)
.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jb_modify)
.addComponent(jb_delete))
.addGap(25, 25, 25))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void jb_modifyActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String id = this.jtf_id.getText();
		String className=this.jtf_className.getText();
		int gradeID=((Grade)this.jcb_grade.getSelectedItem()).getId();
		String classRemark=this.jta_classRemark.getText();
		SchoolClass schoolClass=new SchoolClass(Integer.parseInt(id),className,gradeID,classRemark);
		Connection con=null;
		try {
			con=dbUtil.getCon();
			int num=schoolClassDao.classModify(con, schoolClass);
			if(num==1){
				JOptionPane.showMessageDialog(null, "修改成功");
				this.fillGrade();
				this.fillTable(new SchoolClass());
			}else if(num==2){
				JOptionPane.showMessageDialog(null, "记录并未修改");				
			}else{
				JOptionPane.showMessageDialog(null, "修改失败");
			}
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "修改失败");
			e.printStackTrace();
		}finally{
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
	}

	private void jb_deleteActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String id = this.jtf_id.getText();
		Connection con = null;
		try {
			con = dbUtil.getCon();
			boolean flag=studentDao.getstudentbyclassID(con, Integer.parseInt(id));
			if(flag){
			JOptionPane.showMessageDialog(null, "该班级下还有学生");
			return;
			}			
			int num = schoolClassDao.classDelete(con, id);
			if (num > 0) {
				this.fillGrade();
				this.fillTable(new SchoolClass());
				JOptionPane.showMessageDialog(null, "删除成功");
			} else {
				JOptionPane.showMessageDialog(null, "删除失败");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "删除失败");
		} finally {
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	private void Jt_ClassTableMousePressed(java.awt.event.MouseEvent evt) {
		int row = this.Jt_ClassTable.getSelectedRow();
		this.jtf_id.setText((String) this.Jt_ClassTable.getValueAt(row, 0));
		this.jtf_className.setText((String) this.Jt_ClassTable.getValueAt(row,
				1));
		String grade = (String) this.Jt_ClassTable.getValueAt(row, 2);
		int num = this.jcb_grade.getItemCount();
		for (int i = 0; i < num; i++) {
			Grade currentgrade = (Grade) this.jcb_grade.getItemAt(i);
			if (grade.equals(currentgrade.getGradeName())) {
				this.jcb_grade.setSelectedIndex(i);
			}
		}
		this.jta_classRemark.setText((String) this.Jt_ClassTable.getValueAt(
				row, 3));
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.fillTable(new SchoolClass());
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String schoolclass = this.className_jtf.getText();
		Grade gradeName = (Grade) this.grade_jcb.getSelectedItem();
		SchoolClass schoolClass = new SchoolClass(schoolclass, gradeName
				.getGradeName());
		this.fillTable(schoolClass);

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTable Jt_ClassTable;
	private javax.swing.JTextField className_jtf;
	private javax.swing.JComboBox grade_jcb;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JButton jb_delete;
	private javax.swing.JButton jb_modify;
	private javax.swing.JComboBox jcb_grade;
	private javax.swing.JTextArea jta_classRemark;
	private javax.swing.JTextField jtf_className;
	private javax.swing.JTextField jtf_id;
	// End of variables declaration//GEN-END:variables

}