/*
 * classAddInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.rongjun.zheng.view;

import java.sql.Connection;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

import com.rongjun.zheng.dao.GradeDao;
import com.rongjun.zheng.dao.SchoolClassDao;
import com.rongjun.zheng.model.Grade;
import com.rongjun.zheng.model.SchoolClass;
import com.rongjun.zheng.util.DbUtil;
import com.rongjun.zheng.util.StringUtil;

/**
 *
 * @author  __USER__
 */
public class classAddInterFrm extends javax.swing.JInternalFrame {

	/** Creates new form classAddInterFrm */
	DbUtil dbUtil = new DbUtil();
	GradeDao gradeDao=new GradeDao();
	SchoolClassDao schoolClassDao=new SchoolClassDao();

	public classAddInterFrm() {
		initComponents();
		this.setLocation(200, 100);
		this.filljcb_grade();
	}

	public void filljcb_grade() {
		this.jcb_grade.removeAllItems();
		Connection con = null;
		Grade grade = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = gradeDao.gradeList(con, new Grade());
			while (rs.next()) {
				grade = new Grade();
				grade.setId(rs.getInt(1));
				grade.setGradeName(rs.getString(2));
				grade.setGradeRemark(rs.getString(3));
				this.jcb_grade.addItem(grade);
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jLabel1 = new javax.swing.JLabel();
jb_add = new javax.swing.JButton();
jb_reset = new javax.swing.JButton();
jtf_className = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
jta_classRemark = new javax.swing.JTextArea();
jLabel3 = new javax.swing.JLabel();
jcb_grade = new javax.swing.JComboBox();

setClosable(true);
setIconifiable(true);
setTitle("\u73ed\u7ea7\u4fe1\u606f\u7ba1\u7406");

jLabel1.setText("\u73ed\u7ea7\u540d\u5b57");

jb_add.setText("\u589e\u52a0");
jb_add.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jb_addActionPerformed(evt);
}
});

jb_reset.setText("\u91cd\u7f6e");
jb_reset.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jb_resetActionPerformed(evt);
}
});

jLabel2.setText("\u73ed\u7ea7\u5907\u6ce8");

jta_classRemark.setColumns(20);
jta_classRemark.setRows(5);
jScrollPane1.setViewportView(jta_classRemark);

jLabel3.setText("\u6240\u5c5e\u5e74\u7ea7");



javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(46, 46, 46)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jb_add)
.addGap(39, 39, 39)
.addComponent(jb_reset))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jtf_className))
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
.addComponent(jLabel3)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jcb_grade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
.addComponent(jLabel2)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
.addContainerGap(133, Short.MAX_VALUE))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(21, 21, 21)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1)
.addComponent(jtf_className, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel2)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel3)
.addComponent(jcb_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jb_add)
.addComponent(jb_reset))
.addGap(85, 85, 85))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void jb_addActionPerformed(java.awt.event.ActionEvent evt)  {
		// TODO add your handling code here:
		String className=this.jtf_className.getText();
		String classRemark=this.jta_classRemark.getText();
		Grade grade=(Grade)this.jcb_grade.getSelectedItem();
		int gradeID=grade.getId();
		SchoolClass schoolClass=new SchoolClass(className,gradeID,classRemark);
		if(StringUtil.isEmpty(className)){
			JOptionPane.showMessageDialog(null, "班级名字不能为空");
		}
		Connection con=null;
		try {
			con=dbUtil.getCon();
			int num=schoolClassDao.classAdd(con, schoolClass);
			if(num==2){
				JOptionPane.showMessageDialog(null, "该年段已经有同名记录");
			}else if(num==1){				
				JOptionPane.showMessageDialog(null, "增加成功");
			}
			else{
				JOptionPane.showMessageDialog(null, "增加失败");
				
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "增加失败");
		}finally{
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	private void jb_resetActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.jtf_className.setText("");
		this.jta_classRemark.setText("");
		this.jcb_grade.setSelectedIndex(0);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton jb_add;
	private javax.swing.JButton jb_reset;
	private javax.swing.JComboBox jcb_grade;
	private javax.swing.JTextArea jta_classRemark;
	private javax.swing.JTextField jtf_className;
	// End of variables declaration//GEN-END:variables

}