/*
 * gradeAddInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.rongjun.zheng.view;

import java.sql.Connection;

import javax.swing.JOptionPane;

import com.rongjun.zheng.dao.GradeDao;
import com.rongjun.zheng.model.Grade;
import com.rongjun.zheng.util.DbUtil;
import com.rongjun.zheng.util.StringUtil;

/**
 *
 * @author  __USER__
 */
public class gradeAddInterFrm extends javax.swing.JInternalFrame {
	DbUtil dbUtil = new DbUtil();
	GradeDao gradeDao = new GradeDao();

	/** Creates new form gradeAddInterFrm */
	public gradeAddInterFrm() {
		this.setLocation(400,200);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		gradeName = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		gradeRemark = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setResizable(true);
		setTitle("\u5e74\u7ea7\u4fe1\u606f\u6dfb\u52a0");

		jLabel1.setText("\u5e74\u7ea7\u540d\u5b57:");

		jLabel3.setText("\u5907\u6ce8:");

		gradeRemark.setColumns(20);
		gradeRemark.setRows(5);
		jScrollPane1.setViewportView(gradeRemark);

		jButton1.setText("\u6dfb\u52a0");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u91cd\u7f6e");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(87, 87,
										87).addComponent(jButton1).addGap(38,
										38, 38).addComponent(jButton2).addGap(
										141, 141, 141))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(37, 37, 37)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel1)
														.addComponent(jLabel3))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																225,
																Short.MAX_VALUE)
														.addComponent(
																gradeName,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																225,
																Short.MAX_VALUE))
										.addGap(60, 60, 60)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(35, 35, 35)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																gradeName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												46, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addGap(41, 41, 41)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String gradeName = this.gradeName.getText();
		String gradeRemark = this.gradeRemark.getText();
		if (StringUtil.isEmpty(gradeName)) {
			JOptionPane.showMessageDialog(null, "年级名字不能为空");
		}
		Connection con = null;
		Grade grade = new Grade(gradeName, gradeRemark);
		try {
			con = dbUtil.getCon();
			int num = gradeDao.gradeAdd(con, grade);
			if (num ==2) {
				JOptionPane.showMessageDialog(null, "有同名年级");
				return;
			} else if(num==1){
				JOptionPane.showMessageDialog(null, "年级增加成功");
			}else{
			   JOptionPane.showMessageDialog(null, "年级增加成功");
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "年级增加失败");
			e.printStackTrace();
		} finally {
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		resetValue();
	}

	private void resetValue() {
		this.gradeName.setText("");
		this.gradeRemark.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField gradeName;
	private javax.swing.JTextArea gradeRemark;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}