/*
 * MainFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.rongjun.zheng.view;

import javax.swing.JFrame;

/**
 *
 * @author  __USER__
 */
public class MainFrm extends javax.swing.JFrame {

	/** Creates new form MainFrm */
	public MainFrm() {
		initComponents();
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		TablePane = new javax.swing.JDesktopPane();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu4 = new javax.swing.JMenu();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenu5 = new javax.swing.JMenu();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenuItem1 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5b66\u751f\u4fe1\u606f\u7ba1\u7406\u7cfb\u7edf");
		setResizable(false);

		jMenu1.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\reapir.png")); // NOI18N
		jMenu1.setText("\u6570\u636e\u7ef4\u62a4");

		jMenu4.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\studengmanage.png")); // NOI18N
		jMenu4.setText("\u5b66\u751f\u4fe1\u606f\u7ba1\u7406");

		jMenuItem2.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\add.png")); // NOI18N
		jMenuItem2.setText("\u5b66\u751f\u4fe1\u606f\u6dfb\u52a0");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu4.add(jMenuItem2);

		jMenuItem3.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\student01.png")); // NOI18N
		jMenuItem3.setText("\u5b66\u751f\u4fe1\u606f\u7ef4\u62a4");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu4.add(jMenuItem3);

		jMenu1.add(jMenu4);

		jMenu3.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\classmanage.png")); // NOI18N
		jMenu3.setText("\u73ed\u7ea7\u4fe1\u606f\u7ba1\u7406");

		jMenuItem4.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\add.png")); // NOI18N
		jMenuItem4.setText("\u73ed\u7ea7\u4fe1\u606f\u6dfb\u52a0");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem4);

		jMenuItem5.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\classrepair.png")); // NOI18N
		jMenuItem5.setText("\u73ed\u7ea7\u4fe1\u606f\u7ef4\u62a4");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem5);

		jMenu1.add(jMenu3);

		jMenu5.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\grademanage.png")); // NOI18N
		jMenu5.setText("\u5e74\u7ea7\u4fe1\u606f\u7ba1\u7406");

		jMenuItem6.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\add.png")); // NOI18N
		jMenuItem6.setText("\u5e74\u7ea7\u4fe1\u606f\u6dfb\u52a0");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu5.add(jMenuItem6);

		jMenuItem7.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\graderepair.png")); // NOI18N
		jMenuItem7.setText("\u5e74\u7ea7\u4fe1\u606f\u7ef4\u62a4");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu5.add(jMenuItem7);

		jMenu1.add(jMenu5);

		jMenuItem1.setIcon(new javax.swing.ImageIcon(
				"D:\\workspace\\StuManageSystem\\images\\close.png")); // NOI18N
		jMenuItem1.setText("\u9000\u51fa");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				TablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				TablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 279,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		StudentManageInterFrm studentManageInterFrm = new StudentManageInterFrm();
		this.TablePane.add(studentManageInterFrm);
		studentManageInterFrm.setVisible(true);
	}

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		StudentAddInterFrm studentAddInterFrm = new StudentAddInterFrm();
		this.TablePane.add(studentAddInterFrm);
		studentAddInterFrm.setVisible(true);
	}

	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
		ClassManageInterFrm classManageInterFrm = new ClassManageInterFrm();
		this.TablePane.add(classManageInterFrm);
		classManageInterFrm.setVisible(true);
	}

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
		classAddInterFrm classaddInterFrm = new classAddInterFrm();
		this.TablePane.add(classaddInterFrm);
		classaddInterFrm.setVisible(true);
	}

	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		GradeManageInterFrm gradeManageInterFrm = new GradeManageInterFrm();
		this.TablePane.add(gradeManageInterFrm);
		gradeManageInterFrm.setVisible(true);
	}

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		gradeAddInterFrm gradeaddInterFrm = new gradeAddInterFrm();
		this.TablePane.add(gradeaddInterFrm);
		gradeaddInterFrm.setVisible(true);
	}

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		System.exit(0);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JDesktopPane TablePane;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	// End of variables declaration//GEN-END:variables

}