/*
 * ManagerReginterJD.java
 *
 * Created on __DATE__, __TIME__
 */

package com.rongjun.zheng.view;

import java.sql.Connection;

import javax.swing.JOptionPane;

import com.rongjun.zheng.dao.ManagerDao;
import com.rongjun.zheng.model.Manager;
import com.rongjun.zheng.util.DbUtil;
import com.rongjun.zheng.util.StringUtil;

/**
 *
 * @author  __USER__
 */
public class ManagerReginterJD extends javax.swing.JDialog {
	DbUtil dbUtil=new DbUtil();
	/** Creates new form ManagerReginterJD */
	public ManagerReginterJD() {
		super();
		this.setLocationRelativeTo(null);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		userRegister = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		passwordRegister = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		emailRegister = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setModal(true);

		jLabel1.setText("\u8d26\u53f7\u6ce8\u518c");

		jLabel2.setText("\u5bc6\u7801\u6ce8\u518c");

		jButton1.setText("\u6ce8\u518c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u91cd\u7f6e");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel3.setText("\u90ae\u7bb1\u6ce8\u518c");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(50, 50, 50)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addGap(
																				72,
																				72,
																				72)
																		.addComponent(
																				jButton2))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								emailRegister)
																						.addComponent(
																								passwordRegister)
																						.addComponent(
																								userRegister,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								157,
																								Short.MAX_VALUE))))
										.addContainerGap(141, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(57, 57, 57)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																userRegister,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(30, 30, 30)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																passwordRegister,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																emailRegister,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2))
										.addContainerGap(99, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String userRegister=this.userRegister.getText();
		String passwordRegister=this.passwordRegister.getText();
		String emailRegister=this.emailRegister.getText();
		if(StringUtil.isEmpty(userRegister)){
			JOptionPane.showMessageDialog(null, "用户名不能为空");
			return;
			
		}
		if(StringUtil.isEmpty(passwordRegister)){
			JOptionPane.showMessageDialog(null, "密码不能为空");
			return;
		}
		if(StringUtil.isEmpty(emailRegister)){
			JOptionPane.showMessageDialog(null, "邮箱不能为空");
			return;
		}
		Manager manager=new Manager(userRegister,passwordRegister,emailRegister);
		Connection con=null;
		try {
			con=dbUtil.getCon();
			int num=new ManagerDao().register(con, manager);
			if(num==1){
				JOptionPane.showMessageDialog(null, "注册成功");
				resetValue();
			}else if(num==2){
				JOptionPane.showMessageDialog(null, "有同名账号");
			}else{
				JOptionPane.showMessageDialog(null, "注册失败");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "注册失败");
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		resetValue();
	}

	private void resetValue() {
		this.userRegister.setText("");
		this.passwordRegister.setText("");
		this.emailRegister.setText("");
	}

	/**
	 * @param args the command line arguments
	 */

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField emailRegister;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField passwordRegister;
	private javax.swing.JTextField userRegister;
	// End of variables declaration//GEN-END:variables

}