/*
 * StudentAddInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.rongjun.zheng.view;

import java.sql.Connection;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

import com.rongjun.zheng.dao.SchoolClassDao;
import com.rongjun.zheng.dao.StudentDao;
import com.rongjun.zheng.date.Chooser;
import com.rongjun.zheng.model.SchoolClass;
import com.rongjun.zheng.model.Student;
import com.rongjun.zheng.util.DbUtil;

/**
 *
 * @author  __USER__
 */
public class StudentAddInterFrm extends javax.swing.JInternalFrame {
	DbUtil dbUtil = new DbUtil();
	SchoolClassDao schoolClassDao = new SchoolClassDao();
	StudentDao studentDao=new StudentDao();

	/** Creates new form StudentAddInterFrm */
	public StudentAddInterFrm() {
		initComponents();
		this.fillclass();
		this.setLocation(400, 100);

	}

	public void fillclass() {
		this.jcb_class.removeAllItems();
		Connection con = null;
		SchoolClass schoolClass = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = schoolClassDao.classList(con, new SchoolClass());
			while (rs.next()) {
				schoolClass = new SchoolClass();
				schoolClass.setId(rs.getInt(1));
				schoolClass.setClassName(rs.getString(2));
				schoolClass.setGradeID(rs.getInt(3));
				schoolClass.setClassRemark(rs.getString(4));
				schoolClass.setGradeName(rs.getString(6));
				this.jcb_class.addItem(schoolClass);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	public void date() {
		Chooser ser = Chooser.getInstance();
		ser.register(this.birthday);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jLabel1 = new javax.swing.JLabel();
studentName = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
studentnumber = new javax.swing.JTextField();
jLabel3 = new javax.swing.JLabel();
birthday = new javax.swing.JTextField();
jLabel4 = new javax.swing.JLabel();
nativeplace = new javax.swing.JTextField();
jcb_class = new javax.swing.JComboBox();
jLabel5 = new javax.swing.JLabel();
jLabel7 = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
studentremark = new javax.swing.JTextArea();
studentadd = new javax.swing.JButton();
reset = new javax.swing.JButton();

setClosable(true);
setIconifiable(true);
setTitle("\u5b66\u751f\u589e\u52a0\u7cfb\u7edf");

jLabel1.setText("\u59d3\u540d");

jLabel2.setText("\u5b66\u53f7");

jLabel3.setText("\u751f\u65e5");

jLabel4.setText("\u7c4d\u8d2f");

nativeplace.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
nativeplaceActionPerformed(evt);
}
});

this.date();

jLabel5.setText("\u73ed\u7ea7");

jLabel7.setText("\u5907\u6ce8");

studentremark.setColumns(20);
studentremark.setRows(5);
jScrollPane1.setViewportView(studentremark);

studentadd.setText("\u589e\u52a0");
studentadd.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
studentaddActionPerformed(evt);
}
});

reset.setText("\u91cd\u7f6e");
reset.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
resetActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jLabel1)
.addComponent(jLabel5))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jcb_class, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
.addComponent(birthday, javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(studentName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
.addGap(19, 19, 19)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel2)
.addGroup(layout.createSequentialGroup()
.addGap(3, 3, 3)
.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(nativeplace, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
.addComponent(studentnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))))
.addComponent(jLabel3))
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel7)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(layout.createSequentialGroup()
.addComponent(studentadd)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(reset))
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
.addGap(97, 97, 97))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1)
.addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(9, 9, 9)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3)
.addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel2)
.addComponent(studentnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(9, 9, 9)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel4)
.addComponent(nativeplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel5)
.addComponent(jcb_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel7)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(studentadd)
.addComponent(reset))
.addContainerGap(41, Short.MAX_VALUE))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void studentaddActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String name = this.studentName.getText();
		String studentNumber=this.studentnumber.getText();
		String birthday=this.birthday.getText();
		String nativeplace=this.nativeplace.getText();
		int classid=((SchoolClass)this.jcb_class.getSelectedItem()).getId();
		String studentremark=this.studentremark.getText();
		Student student=new Student(studentNumber, name, birthday, nativeplace, classid, studentremark);
		Connection con=null;
		try {
			con=dbUtil.getCon();
			int num=studentDao.studentAdd(con, student);
			if(num==2){
				JOptionPane.showMessageDialog(null, "该班已经有同名学生");
			}else if(num==1){				
				JOptionPane.showMessageDialog(null, "增加成功");
			}
			else{
				JOptionPane.showMessageDialog(null, "增加失败");
				
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "增加失败");
		}finally{
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	private void resetActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.studentName.setText("");
		this.studentnumber.setText("");
		this.birthday.setText("");
		this.nativeplace.setText("");
		this.jcb_class.setSelectedIndex(-1);
		this.studentremark.setText("");
	}

	private void nativeplaceActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField birthday;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JComboBox jcb_class;
	private javax.swing.JTextField nativeplace;
	private javax.swing.JButton reset;
	private javax.swing.JTextField studentName;
	private javax.swing.JButton studentadd;
	private javax.swing.JTextField studentnumber;
	private javax.swing.JTextArea studentremark;
	// End of variables declaration//GEN-END:variables

}