/*
 * StudentManageInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.rongjun.zheng.view;

import java.sql.Connection;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.rongjun.zheng.dao.SchoolClassDao;
import com.rongjun.zheng.dao.StudentDao;
import com.rongjun.zheng.date.Chooser;
import com.rongjun.zheng.model.SchoolClass;
import com.rongjun.zheng.model.Student;
import com.rongjun.zheng.util.DbUtil;

/**
 *
 * @author  __USER__
 */
public class StudentManageInterFrm extends javax.swing.JInternalFrame {
	DbUtil dbUtil = new DbUtil();
	SchoolClassDao schoolClassDao = new SchoolClassDao();
	StudentDao studentDao = new StudentDao();

	/** Creates new form StudentManageInterFrm */
	public StudentManageInterFrm() {
		initComponents();
		this.setLocation(300, 100);
		this.fillclass();
		this.filltable(new Student());
	}

	public void date() {
		Chooser ser = Chooser.getInstance();
		ser.register(this.birthday);
	}

	public void filltable(Student student) {
		DefaultTableModel tm = (DefaultTableModel) this.jTable1.getModel();
		tm.setRowCount(0);
		Connection con = null;
		SchoolClass schoolClass = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = studentDao.studentList(con, student);
			while (rs.next()) {
				String tableclass = null;
				int num = rs.getInt(6);
				for (int i = 0; i < this.studentclass.getItemCount(); i++) {
					schoolClass = (SchoolClass) this.studentclass.getItemAt(i);
					if (schoolClass.getId() == num) {
						tableclass = schoolClass.getGradeName()
								+ schoolClass.getClassName();
					}
				}
				String[] row = { rs.getInt(1) + "", rs.getString(2),
						rs.getString(3), rs.getString(4), rs.getString(5),
						tableclass, rs.getString(7) };
				tm.addRow(row);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	public void fillclass() {
		this.studentclass.removeAllItems();
		this.jComboBox2.removeAllItems();
		Connection con = null;
		SchoolClass schoolClass = null;
		try {
			con = dbUtil.getCon();
			ResultSet rs = schoolClassDao.classList(con, new SchoolClass());
			while (rs.next()) {
				schoolClass = new SchoolClass();
				schoolClass.setId(rs.getInt(1));
				schoolClass.setClassName(rs.getString(2));
				schoolClass.setGradeID(rs.getInt(3));
				schoolClass.setClassRemark(rs.getString(4));
				schoolClass.setGradeName(rs.getString(6));
				this.studentclass.addItem(schoolClass);
				this.jComboBox2.addItem(schoolClass);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jScrollPane1 = new javax.swing.JScrollPane();
jTable1 = new javax.swing.JTable();
jLabel1 = new javax.swing.JLabel();
studentName = new javax.swing.JTextField();
studentclass = new javax.swing.JComboBox();
jLabel2 = new javax.swing.JLabel();
jLabel3 = new javax.swing.JLabel();
studentid = new javax.swing.JTextField();
jLabel4 = new javax.swing.JLabel();
studentnumber = new javax.swing.JTextField();
jLabel5 = new javax.swing.JLabel();
name = new javax.swing.JTextField();
jLabel6 = new javax.swing.JLabel();
birthday = new javax.swing.JTextField();
jLabel7 = new javax.swing.JLabel();
nativeplace = new javax.swing.JTextField();
jLabel8 = new javax.swing.JLabel();
jLabel9 = new javax.swing.JLabel();
jScrollPane2 = new javax.swing.JScrollPane();
studentRemark = new javax.swing.JTextArea();
jButton1 = new javax.swing.JButton();
jButton2 = new javax.swing.JButton();
jComboBox2 = new javax.swing.JComboBox();
jButton3 = new javax.swing.JButton();
jButton4 = new javax.swing.JButton();

setClosable(true);
setIconifiable(true);
setTitle("\u5b66\u751f\u4fe1\u606f\u7ef4\u62a4");

jTable1.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		
	},
	new String [] {
		"±àºÅ", "Ñ§ºÅ", "ÐÕÃû", "ÉúÈÕ", "¼®¹á", "°à¼¶", "Ñ§Éú±¸×¢"
	}
) {
	boolean[] canEdit = new boolean [] {
		false, true, true, true, true, true, true
	};

	public boolean isCellEditable(int rowIndex, int columnIndex) {
		return canEdit [columnIndex];
	}
});
jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
public void mousePressed(java.awt.event.MouseEvent evt) {
jTable1MousePressed(evt);
}
});
jScrollPane1.setViewportView(jTable1);

jLabel1.setText("\u5b66\u751f\u59d3\u540d");


jLabel2.setText("\u73ed\u7ea7");

jLabel3.setText("\u7f16\u53f7");

studentid.setEditable(false);

jLabel4.setText("\u5b66\u53f7");

jLabel5.setText("\u59d3\u540d");

jLabel6.setText("\u751f\u65e5");

jLabel7.setText("\u7c4d\u8d2f");

jLabel8.setText("\u73ed\u7ea7");

jLabel9.setText("\u5b66\u751f\u5907\u6ce8");

studentRemark.setColumns(20);
studentRemark.setRows(5);
jScrollPane2.setViewportView(studentRemark);

jButton1.setText("\u4fee\u6539");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});

jButton2.setText("\u5220\u9664");
jButton2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton2ActionPerformed(evt);
}
});

this.date();

jButton3.setText("\u67e5\u8be2");
jButton3.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton3ActionPerformed(evt);
}
});

jButton4.setText("\u5168\u90e8\u663e\u793a");
jButton4.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton4ActionPerformed(evt);
}
});

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(52, 52, 52)
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(61, 61, 61)
.addComponent(jLabel2)
.addGap(18, 18, 18)
.addComponent(studentclass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(28, 28, 28)
.addComponent(jButton3)
.addGap(18, 18, 18)
.addComponent(jButton4))
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
.addGroup(layout.createSequentialGroup()
.addGap(10, 10, 10)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addComponent(jLabel6)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel3)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jButton1)
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
.addComponent(birthday, javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(studentid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
.addGap(4, 4, 4)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel4)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(studentnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jButton2)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel7)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(nativeplace, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(18, 18, 18)
.addComponent(jLabel8))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel5)))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel9))
.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
.addContainerGap())
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1)
.addComponent(studentclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel2)
.addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton3)
.addComponent(jButton4))
.addGap(6, 6, 6)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3)
.addComponent(jLabel5)
.addComponent(jLabel9)
.addComponent(jLabel4)
.addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(studentnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel6)
.addComponent(jLabel8)
.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel7)
.addComponent(nativeplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jButton1)
.addComponent(jButton2)))
.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addContainerGap(43, Short.MAX_VALUE))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		int id=Integer.parseInt(this.studentid.getText());
		String studentNumber=this.studentnumber.getText();
		String name=this.name.getText();
		String birthday=this.birthday.getText();
		String nativeplace=this.nativeplace.getText();
		int classId = ((SchoolClass) this.jComboBox2.getSelectedItem())
		.getId();
		String studentRemark=this.studentRemark.getText();
		Student student=new Student(id, studentNumber, name, birthday, nativeplace, 
				classId, studentRemark);
		Connection con=null;
		try {
			con=dbUtil.getCon();
			int num=studentDao.StudentModify(con, student);
			if(num==1){
				JOptionPane.showMessageDialog(null, "ÐÞ¸Ä³É¹¦");
				this.fillclass();
				this.filltable(new Student());
			}else if(num==2){
				JOptionPane.showMessageDialog(null, "¼ÇÂ¼²¢Î´ÐÞ¸Ä");				
			}else{
				JOptionPane.showMessageDialog(null, "ÐÞ¸ÄÊ§°Ü");
			}
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "ÐÞ¸ÄÊ§°Ü");
			e.printStackTrace();
		}finally{
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		
	}


	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.filltable(new Student());
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String name = this.studentName.getText();
		int classId = ((SchoolClass) this.studentclass.getSelectedItem())
				.getId();
		Student student = new Student();
		student.setName(name);
		student.setClassid(classId);
		this.filltable(student);
	}

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		int row = this.jTable1.getSelectedRow();
		this.studentid.setText((String) this.jTable1.getValueAt(row, 0));
		this.studentnumber.setText((String) this.jTable1.getValueAt(row, 1));
		this.name.setText((String) this.jTable1.getValueAt(row, 2));
		this.birthday.setText((String) this.jTable1.getValueAt(row, 3));
		this.nativeplace.setText((String) this.jTable1.getValueAt(row, 4));
		String currentclass = (String) this.jTable1.getValueAt(row, 5);
		int num = this.jComboBox2.getItemCount();
		for (int i = 0; i < num; i++) {
			String studentclass = this.jComboBox2.getItemAt(i).toString();
			if (studentclass.equals(currentclass)) {
				this.jComboBox2.setSelectedIndex(i);
			}
		}
		this.studentRemark.setText((String) this.jTable1.getValueAt(row, 6));
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String id = this.studentid.getText();
		Connection con = null;
		try {
			con = dbUtil.getCon();
			int num = studentDao.studentDelete(con, id);
			if (num > 0) {
				JOptionPane.showMessageDialog(null, "É¾³ý³É¹¦");
				this.fillclass();
				this.filltable(new Student());
			} else {
				JOptionPane.showMessageDialog(null, "É¾³ýÊ§°Ü");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "É¾³ýÊ§°Ü");
			e.printStackTrace();
		} finally {
			try {
				dbUtil.close(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField birthday;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField name;
	private javax.swing.JTextField nativeplace;
	private javax.swing.JTextField studentName;
	private javax.swing.JTextArea studentRemark;
	private javax.swing.JComboBox studentclass;
	private javax.swing.JTextField studentid;
	private javax.swing.JTextField studentnumber;
	// End of variables declaration//GEN-END:variables

}